config/routes.rb
Rails.application.routes.draw do
resources :thoughts


root to: 'profile#index'
get 'index' => 'profile#index'

get '/login' => 'sessions#login'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#signup'
post '/users'=> 'users#create'
#
# get '/thoughts' => "thoughts#index", as: 'thoughts'
# get '/thoughts/new' => "thoughts#new", as: 'new_thought'
# post '/thoughts' =>'thoughts#create'
# delete "/thoughts/:id" => "thoughts#destroy", as: 'destroy_thought_path'
#
# get '/thoughts/:id/edit', 'thoughts#edit'
# patch '/thoughts/:id', 'thoughts#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thought.rb
class Thought < ApplicationRecord
belongs_to :users, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :thoughts
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to '/login' unless current_user
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
before_filter :authorize

  def index

  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
   user = User.find_by_email(params[:email])
   # If the user exists AND the password entered is correct.
   if user && user.authenticate(params[:password])
     # Save the user id inside the browser cookie. This is how we keep the user
     # logged in when they navigate around our website.
     session[:user_id] = user.id
     redirect_to '/'
   else
   # If user's login doesn't work, send them back to the login form.
     redirect_to '/login'
   end
 end

 def destroy
   session[:user_id] = nil
   redirect_to '/login'
 end

end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController

  def index
  @thoughts = Thought.all
  end

#   def show
#     thought_id = params[:id]
#     @thought = Thought.find(thought_id)
#   end
#
  def new
    @thought = Thought.new()
  end

  def create
  Thought.create(thought_params)
  redirect_to('/thoughts')
end

def edit
  thought_id = params[:id]
  @thought = Thought.find(thought_id)
end

def update
  thought_id = params[:id]
  @thought = Thought.find(thought_id)

  if @thought.update(thought_params)
    redirect_to ("/thoughts")
  else
    render 'edit'
  end
end

def destroy
  thought_id = params[:id]
  @thought = Thought.find(thought_id)
  @thought.destroy

  redirect_to('/thoughts')
end

private # Everything below is only able to be used in this controller

def thought_params
  params.require(:thought).permit(:description, :category)

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rails_OurThoughtsAppRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/thoughts/edit.html.erb
<div class="form">
<%= form_for @thought do |f| %>
  <span>Title: </span>
  <%= f.text_field :description, required: true %><br>
  <span>Category: </span>
  <%= f.text_field :category, required: true %><br>
  <%= f.submit %>
<% end %>
</div>

app/views/thoughts/index.html.erb
<h1>ALL THOUGHTS</h1>

<%= link_to "Make a New Thought", new_thought_path %>

</br>
<% @thoughts.each do |thought|%>
<div class= "card">

<p>Title: <%=thought.description%></p>
<p>Category: <%=thought.category%> </p>
<button><%= link_to 'Edit', edit_thought_path(thought) %> </button>
<button> <%= link_to "Destroy", thought, method: :delete, data:{confirm: "Are you sure?"} %> </button>
</div>
  <%end%>

app/views/thoughts/new.html.erb
<div class="form">
<%= form_for @thought do |f| %>
  <span>Title: </span>
  <%= f.text_field :description, required: true %><br>
  <span>Category: </span>
  <%= f.text_field :category, required: true %><br>
  <%= f.submit %>
<% end %>
</div>

app/views/users/signup.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Phone: <%= f.text_field :phone %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>